### ISSUE TITLE
Segfault / "invalid device function" in `DeviceReduce::Sum`

### ISSUE THREAD

**Issue by e-kayrakli** [ROCmSoftwarePlatform/hipCUB#304] opened 2023-10-18 21:44 UTC
I am trying to use `DeviceReduce::Sum` but:

- with ROCm 5.4.3, I get a segfault,
- with ROCm 5.6.1 and 5.7.0, I get `HIP error: invalid device function` on the line where actual reduction takes place.

The context here is to add an initial reduction support for AMD GPUs in Chapel ([chapel-lang.org](https://chapel-lang.org/)), so my actual use case is a bit complicated. However, in my system I was able to reproduce the behavior with a standalone test based on [this unit test](https://github.com/ROCmSoftwarePlatform/hipCUB/blob/develop/test/hipcub/test_hipcub_device_reduce.cpp). Full code is at the end of my post.

I have:

```
> hipcc --version
HIP version: 5.6.31062-73ed8adfd
```

and compile the code with

```
> hipcc --std=c++14 reduceTest.cpp
```

I am trying to run this on an MI250x.

I can provide more details.
<details> <summary> Reproducer </summary>

```cpp
#include <iostream>
#include <vector>
#include <hip/hip_runtime.h>
#include <hip/hip_runtime_api.h>
#include <hip/hip_common.h>
#include <hipcub/hipcub.hpp>

#define HIP_CHECK(condition)         \
{                                    \
  hipError_t error = condition;    \
  if(error != hipSuccess){         \
    std::cout << "HIP error: " << hipGetErrorString(error) << " line: " << __LINE__ << std::endl; \
    exit(error); \
  } \
}

int main(int argc, char* argv[]) {
  using T = int;
  using U = int;
  int device_id = 0;
  HIP_CHECK(hipSetDevice(device_id));

  size_t size = 1000;

  bool debug_synchronous = true;

  hipStream_t stream = 0; // default

  // Generate data
  std::vector<T> input(1, (U) 0.0f);
  std::vector<U> output(1, (U) 0.0f);

  T * d_input;
  U * d_output;
  HIP_CHECK(hipMalloc(&d_input, input.size() * sizeof(T)));
  HIP_CHECK(hipMalloc(&d_output, output.size() * sizeof(U)));
  HIP_CHECK(
      hipMemcpy(
        d_input, input.data(),
        input.size() * sizeof(T),
        hipMemcpyHostToDevice
        )
      );
  HIP_CHECK(hipDeviceSynchronize());

  // Calculate expected results on host
  U expected = U(0.0f);
  for(unsigned int i = 0; i < input.size(); i++)
  {
    expected = expected + (U) input[i];
  }

  // temp storage
  size_t temp_storage_size_bytes;
  void * d_temp_storage = nullptr;
  // Get size of d_temp_storage
  HIP_CHECK(
      hipcub::DeviceReduce::Sum(
        d_temp_storage, temp_storage_size_bytes,
        d_input, d_output, input.size(),
        stream, debug_synchronous
        )
      );

  // temp_storage_size_bytes must be >0
  assert(temp_storage_size_bytes > 0U);

  // allocate temporary storage
  HIP_CHECK(hipMalloc(&d_temp_storage, temp_storage_size_bytes));
  HIP_CHECK(hipDeviceSynchronize());

  // Run
  HIP_CHECK(
      hipcub::DeviceReduce::Sum(
        d_temp_storage, temp_storage_size_bytes,
        d_input, d_output, input.size(),
        stream, debug_synchronous
        )
      );
  HIP_CHECK(hipPeekAtLastError());
  HIP_CHECK(hipDeviceSynchronize());

  // Copy output to host
  HIP_CHECK(
      hipMemcpy(
        output.data(), d_output,
        output.size() * sizeof(U),
        hipMemcpyDeviceToHost
        )
      );
  HIP_CHECK(hipDeviceSynchronize());

  hipFree(d_input);
  hipFree(d_output);
  hipFree(d_temp_storage);

}
```

</details>

**Comment by stanleytsang-amd** [comment] 2023-10-27 21:23
Hi @e-kayrakli, I am unable to reproduce the error you're seeing.  I'm trying a ROCm 5.6 docker image with a very similar compiler build as yours, with the 5.6 releases of rocPRIM/hipCUB.  It all compiles and runs fine for me.  Your code looks pretty normal to me.

Can you run your build command with --verbose and paste the output here?  Is it correctly generating a binary for gfx90a?

**Comment by stanleytsang-amd** [comment] 2023-11-07 17:39
Glad to hear we were able to figure out the problem!  As for your question, from my experience, anytime I see `HIP error: invalid device function` or `hipErrorNoBinaryForGpu: Couldn't find binary for current devices` my first assumption will be that the binary was not compiled for your current GPU architecture.  Typically I see the second message when trying to run a kernel under such conditions and the first message when trying to run a device function, so I assume hipcub::DeviceReduce ran a device function first before running a kernel.

If you want something at a lower level in the ROCm stack...you'd have to make that request elsewhere.  Maybe try the official HIP repository: https://github.com/ROCm-Developer-Tools/HIP

**Comment by stanleytsang-amd** [comment] 2023-11-07 17:40
Closing ticket as issue is resolved.

**Closed by stanleytsang-amd** 2023-11-07 17:40 UTC
